# Generated by Django 4.1.3 on 2022-11-25 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='todo',
            field=models.JSONField(default={}, null=True),
        ),
    ]
