# Generated by Django 4.1.3 on 2022-12-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0005_alter_users_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='todo',
            field=models.JSONField(null=True),
        ),
    ]
